pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/HarshitJain1924/grilli-restaurant-website.git'  // Replace with actual repo
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build('grilli-site')
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    docker.image('grilli-site').run('-p 8080:80')
                }
            }
        }
    }
}
